{% set name = "knoten" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/USGS-Astrogeology/knoten/archive/{{ version }}.tar.gz
  sha256: 6bb833a2eebcbce9e33d4ba843e235e180c66678537368a868cbc21f3e850d3d

build:
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - ale >=0.3.2
    - python >={{ python_min }}
    - csmapi >=1.0
    - gdal >=3.0.0
    - jinja2
    - numpy
    - plio
    - pyproj
    - requests
    - scipy
    - shapely
    - usgscsm >=1.3.1

test:
  imports:
    - knoten
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/USGS-Astrogeology/knoten
  summary: 'A library to leverage python wrapped Community Sensor Models (CSMs) for common spatial/sensor operations and testing.'
  description: 'Basic python tools for CSM camera models'
  doc_url: https://github.com/USGS-Astrogeology/knoten#readme
  dev_url: https://github.com/USGS-Astrogeology/knoten
  license: CC0-1.0
  license_file: LICENSE.md

extra:
  recipe-maintainers:
    - amystamile-usgs
    - acpaquette
    - Kelvinrr
